### ISSUE TITLE
FlpiR integration dans Home Assistant ! Top

### ISSUE THREAD

**Issue by vincentsticky** [cnico/hacs-flipr#1]
Bonjour
Je suis super content de voir qu'une intégration existe désormais pour le FlipR dans Home Assistant (2021.4.6 

Je suis en train de re démarrer ma piscine et suis en attente d'une batterie de la part de FlipR pour pouvoir voir les valeurs (plus de 10j pour envoyer une batterie ... et 9 jours d'attente pour séchage)
mais pour l'instant j'ai bien installé le composant et il se connecte bien puisqu'il récupère l'information comme quoi j'ai un flipr avec le bon numéro de série. Le FlipR étant Off je n'ai pas de valeurs donc je pense normal qu'il n'y ait pas d'entité (temp, taux chlore, ...)

Je ferai des tests et n'hésiterai pas à vous informer si ca ne vous pose pas de probleme

Cordialement

**Comment by cnico** [comment]
Bonjour @vincentsticky, 

Content que mon travail puisse être utile à d'autres.
Oui, c'est normal que si aucune valeur ne remonte des données du Flipr dans leur cloud, il n'y ait pas d'entités qui soient créées. Ca viendra quand votre flipr sera opérationnel je pense.

Sachez que j'essaie de faire adopter à la communauté homeassistant le fait de mettre cette intégration dans le produit directement sans passer par HACS et les composants custom. C'est plus long mais je pense que c'est utile notamment car les développeurs de homeassistant m'apportent des améliorations. 
Ce travail en cours peut être suivi ici : https://github.com/home-assistant/core/pull/46582

Si vous avez des problèmes, n'hésitez pas à me dire.

Je vais fermer cette issue dans l'immédiat et vous pourrez en ouvrir une autre si besoin.

Cordialement,
