### ISSUE TITLE
When the official HomeAssistant flipr integration will be released?

### ISSUE THREAD

**Issue by tmenguy** [cnico/hacs-flipr#2]
All in the title :)]
Thx!

**Comment by cnico** [comment]
Hi,

I don't know the date and I follow the homeassistant community process for this pull request :
https://github.com/home-assistant/core/pull/46582

For me as soon as possible but I can do nothing...

**Comment by tmenguy** [comment]
Merci! Je m’en doutais un peu :) bonne chance, vu les commentaires de la PR ca n’a pas l’air immédiat …..
