### ISSUE TITLE
Hub addition

### ISSUE THREAD

**Issue by lseufer** [cnico/hacs-flipr#3]
Any chance you add the Flipr hub so that we can turn it on and off from HA?

Thanks.

**Comment by cnico** [comment]
Hi, I have not any Flipr hub and I do not plan to buy one since I use a sonoff to start and stop my pool pump.
One contributor has proposed a PR on the flipr api that handle the hub's api.
Feel free to propose a PR on this integration to add flipr's hub entity to homeassistant.

**Comment by cnico** [comment]
For information, I have a pull request on it that I will analyze : https://github.com/cnico/hacs-flipr/pull/5
