### ISSUE TITLE
Mauvais requirement pour flipr-api ?

### ISSUE THREAD

**Issue by Pol2Tls** [cnico/hacs-flipr#4]
Bonjour,
Le "print" trop détaillé est toujours visible mais je vois que ça a bien été corrigé.
Ne faut-il pas appeler la version 1.4.1 au lieu de 1.4.0 dans le manifest.json ?

**Comment by cnico** [comment]
Bonjour, 
Oui, en effet, je l'ai vu en travaillant sur la version officielle qui n'est toujours pas mergée par la communauté homeassistant.
Je viens de faire la modif ici aussi.
