### ISSUE TITLE
Flipr : offcial on homeassistant: there is no binary sensor anymore

### ISSUE THREAD

**Issue by tmenguy** [cnico/hacs-flipr#6]
Hi,

Thanks a lot for the great flipr home assistant integration, was working like a charm on HACS … now using the “official” one … put 2 entites seems to have been removed, the binary sensors.

In the official doc I see:

Leave binary_sensor.flipr_[fliprid]_ph_status and binary_sensor.flipr_[fliprid]_chlorine_status as badges.

Issue is that I want to map those two binary sensors into homekit, was working great in the HACS version, but now there are not prresent anymore … and I have no clue about the notion of “badges” … could you help here? 
Either pointing me to a example to use this notion of badge … or put them back in the official build :)

Thanks anyway for your work.
BR
Thomas

**Comment by cnico** [comment]
Hi, 
I have seen your ticket and responded to it here : https://github.com/home-assistant/home-assistant.io/issues/19065

The problem is not relative to hacs-flipr. So I close the ticket.

I have no better solution than to ask the HA commiter to validate the pull request for the binary sensor...

**Comment by tmenguy** [comment]
Yes you are right, not related to HACS version… so will wait for the official one to be merged then! 
thanks again for the integration.
Thomas
